= Selenium-Jupiter
Boni García
Version {project-version}

:revnumber: {project-version}

== Motivation
https://seleniumhq.github.io/docs/site/en/webdriver/[Selenium WebDriver] is a library that allows controlling web browsers programmatically. It provides a cross-browser API that can be used to drive web browsers (e.g., Chrome, Edge, or Firefox, among others) using different programming languages (e.g., Java, JavaScript, Python, C#, or Ruby). The primary use of Selenium WebDriver is implementing automated tests for web applications. For this reason, it is a common practice to embed the calls to the Selenium WebDriver API in tests implemented using a unit testing framework like JUnit.

https://junit.org/junit5/[JUnit 5] is the next generation of the popular testing framework JUnit. It provides a brand-new programming and extension model called _Jupiter_. The comprehensive nature of Jupiter is very convenient to develop Selenium WebDriver tests on the top of JUnit 5.

.What is Selenium-Jupiter?
****
https://github.com/bonigarcia/selenium-jupiter[Selenium-Jupiter] is an open-source Java library that implements a JUnit 5 extension for developing Selenium WebDriver tests. Selenium-Jupiter uses several features of the Jupiter extension (such as parameters resolution, test templates, or conditional test execution). Thanks to this, the resulting Selenium-Jupiter tests follow a minimalist approach (i.e., the required boilerplate code for WebDriver is reduced) while providing a wide range of advanced features for end-to-end testing.
****

== Setup
Selenium-Jupiter should be used as a Java dependency. We typically use a _build tool_ (such as https://maven.apache.org/[Maven] or https://gradle.org/[Gradle]) to resolve the Selenium-Jupiter dependency. In Maven, it can be done as follows (notice that it is declared using the `test` scope, since it is typically used in tests clasess):

[source,xml]
<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>selenium-jupiter</artifactId>
    <version>4.0.0</version>
    <scope>test</scope>
</dependency>

In the case of a Gradle project, we can declare Selenium-Jupiter as follows (again, for tests):

[source,json]
dependencies {
    testImplementation("io.github.bonigarcia:selenium-jupiter:4.0.0")
}

== Features
Selenium-Jupiter provides an extension class for Jupiter tests called `SeleniumJupiter` (available in the package `io.github.bonigarcia.seljup`). This extension class should be used as a parameter in the annotation `@ExtendWith` (or `@RegisterExtension`) of a Jupiter test.

=== Local browsers
At first glance, Selenium-Jupiter allows using of local browsers (e.g., Chrome, Firefox, Edge, etc.) seamlessly. To that aim, Selenium-Jupiter uses the _parameter resolution_ mechanism provided by Jupiter. This way, we simply need to declare a parameter of the `WebDriver` hierarchy (e.g., `ChromeDriver` to control Chrome, `FirefoxDriver` to control Firefox, etc.) as a test parameter. Internally, Selenium-Jupiter uses https://bonigarcia.org/webdrivermanager/[WebDriverManager] to manage the required driver (e.g., chromedriver for Chrome) before starting the test. Then, it instantiates the `WebDriver` object and injects it into the test. Finally, it terminates the browser gracefully. All in all, the required boilerplate of a test using Selenium WebDriver and Selenium-Jupiter is reduced to the minimum. The following test shows a basic example of this feature:

[source,java]
----
include::../../test/java/io/github/bonigarcia/seljup/test/local/ChromeJupiterTest.java[tags=snippet-in-doc,indent=0]
----

The possible `WebDriver` types we can specify as test parameters are `FirefoxDriver` (see https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/local/FirefoxJupiterTest.java[example]), `EdgeDriver` (see https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/local/EdgeJupiterTest.java[example]), `SafariDriver` (see https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/local/SafariJupiterTest.java[example]), `OperaDriver` (see https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/local/OperaJupiterTest.java[example]), `InternetExplorerDriver` (see https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/local/IExplorerJupiterTest.java[example]), and `ChromiumDriver` (see https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/local/ChromiumJupiterTest.java[example]).

WARNING: Most of the features provided by Selenium-Jupiter can be used in conjunction with Selenium WebDriver versions 3 and 4. Nevertheless, some of them (e.g., the class `ChromiumDriver` to control Chromium browsers) are only available in Selenium WebDriver 4.

=== Conditional tests
Selenium-Jupiter provides the class-level annotation `@EnabledIfBrowserAvailable` to conditionally skip tests. Thanks to this annotation, a test is skipped when the browser specified as a parameter is not available in the system. This capability allows executing the same test suite in different machines (e.g., a local Mac OS with Safari and a Linux CI server) independently of the browser availability. The following example shows a test that is skipped if Safari is not in the system.

[source,java]
----
include::../../test/java/io/github/bonigarcia/seljup/test/local/SafariJupiterTest.java[tags=snippet-in-doc,indent=0]
----

=== Remote browsers
Selenium-Jupiter also allows controlling remote browsers. These browsers are typically provided by a https://www.selenium.dev/documentation/en/grid/[Selenium Grid] infrastructure or a cloud provider (such as https://saucelabs.com/[Sauce Labs], https://www.browserstack.com/[BrowserStack], https://crossbrowsertesting.com/[CrossBrowserTesting], etc.). To this aim, Selenium-Jupiter provides two annotations:

* `@DriverUrl`:  Annotation used to identify the URL of the Selenium Server.
* `@DriverCapabilities`:  Annotation used to configure the desired capabilities, such as the browser type, version, platform, etc.

Both annotations can be defined at parameter or field-level. The following example shows a test using these annotations at the parameter-level. This example uses Selenium Grid in standalone mode to start a Selenium Server listening to port 4444 and hosting a Firefox browser. Notice that the type of parameter injected in the test is the generic `WebDriver` interface (it could also be `RemoteWebDriver`).

[source,java]
----
include::../../test/java/io/github/bonigarcia/seljup/test/remote/RemoteFirefoxJupiterTest.java[tags=snippet-in-doc,indent=0]
----

You can find an example of an equivalent remote test but defining the remote URL and capabilities at field-level https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/remote/RemoteChromeJupiterTest.java[here]. A similar example, but using Sauce Labs is this https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/remote/SauceLabsJupiterTest.java[one].

=== Docker browsers
Selenium-Jupiter allows using browsers in Docker containers in an effortless manner. To that aim, we need to associate the `@DockerBrowser` annotation to parameters of the type `WebDriver` or `RemoteWebDriver` in Jupiter tests. Simply with that, Selenium-Jupiter discovers the latest version of the browser in Docker Hub, pulls this image (if necessary), and starts the browser in the Docker container. The following example shows how to use this feature with a Chrome browser in Docker:

[source,java]
----
include::../../test/java/io/github/bonigarcia/seljup/test/docker/DockerChromeJupiterTest.java[tags=snippet-in-doc,indent=0]
----

The used Docker images by Selenium-Jupiter have been created and maintained by https://aerokube.com/images/latest/[Aerokube]. Therefore, the available browsers to be executed as Docker containers in WebDriverManager are https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/docker/DockerChromeJupiterTest.java[Chrome], https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/docker/DockerFirefoxJupiterTest.java[Firefox], https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/docker/DockerEdgeJupiterTest.java[Edge], https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/docker/DockerOperaJupiterTest.java[Opera], https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/docker/DockerSafariJupiterTest.java[Safari], and https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/docker/DockerChromeMobileJupiterTest.java[Chrome Mobile].

NOTE: The case of Safari is particular since a real Safari browser can only be executed under a Mac OS machine. This way, the Safari Docker containers use the https://webkit.org/[WebKit engine]. This engine is the same used in browser containers, and therefore, from a functional point of view, both browsers (a real Safari and this Docker image) should behave in the same way.

WARNING: Notice that a hardware server or virtual machine with nested virtualization support is required to run Chrome Mobile images.

==== Recordings
==== VNC
==== Performance tests

=== Capabilities
(options, arguments, preferences, binary, extensions)

=== Template tests
=== Generic driver
=== Single session
=== Integration with Jenkins


== Examples
The following repositories contain different examples using Selenium-Jupiter:

* https://github.com/bonigarcia/selenium-jupiter-examples[Selenium-Jupiter Examples]: Different examples with JUnit 5, Selenium WebDriver, and Selenium-Jupiter.

== Advanced Configuration
Selenium-Jupiter provides different ways of configuration. First, by using its _Java API_. 

The second alternative to tune Selenium-Jupiter is using _Java system properties_.  In this method, each Selenium-Jupiter API method has its equivalence of one of a unique _configuration key_. For instance, the API method `cachePath()` (used to specify the driver cache folder) is equivalent to the configuration key `wdm.cachePath`. These types of configuration keys can be passed when executing the tests, for example, using Maven:

[source,shell]
----
mvn test -Dwdm.cachePath=/custom/path/to/driver/cache
----

The third way to configure Selenium-Jupiter is using _environmental variables_. The names for these variables are made from converting each configuration key name (e.g., `wdm.cachePath`) to uppercase and replacing the symbol `.` with `_` (e.g., `WDM_CACHEPATH`). These variables can be helpful to global setup parameters at the operating system level. Also, it allows specifying a custom setup when using Selenium-Jupiter as a Docker container. For example:

[source,shell]
----
docker run --rm -v ${PWD}:/wdm -e ARGS="resolveDriverFor=chrome" -e WDM_CHROMEVERSION=84 bonigarcia/selenium-jupiter:4.0.0
----

NOTE: The preference order of these configuration alternatives is (in case of overlapping) is: 1) Environmental Variables. 2) Java system properties. 3) Java API.

The remainder of this section describes all the possible Java methods in the Selenium-Jupiter API and its equivalent configuration keys in three groups of capabilities: driver management, browsers in Docker, and Selenium-Jupiter Server.

[[server_config]]
.Configuration capabilities for Selenium-Jupiter Server
[options="header"]
|=======
|API method|Configuration key|Default value|Description
|`serverPort(int)`|`wdm.serverPort`|`4444`|Port of Selenium-Jupiter Server
|`serverPath(String)`|`wdm.serverPath`|`/`|Path of Selenium-Jupiter Server
|`serverTimeoutSec(int)`|`wdm.serverTimeoutSec`|`60`|Timeout (in seconds) for Selenium-Jupiter server
|=======

== Known Issues
[discrete]
==== HTTP response code 403
Some of the drivers (e.g., geckodriver or operadriver) are hosted on GitHub. When external clients (like Selenium-Jupiter) makes many consecutive requests to GitHub, and due to its traffic rate limit, it eventually responds with an HTTP 403 error (_forbidden_), as follows:

[source]
----
io.github.bonigarcia.wdm.config.WebDriverManagerException: Error HTTP 403 executing https://api.github.com/repos/mozilla/geckodriver/releases
    at io.github.bonigarcia.wdm.online.HttpClient.execute(HttpClient.java:172)
    at io.github.bonigarcia.wdm.WebDriverManager.openGitHubConnection(WebDriverManager.java:1266)
    at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromGitHub(WebDriverManager.java:1280)
    at io.github.bonigarcia.wdm.managers.FirefoxDriverManager.getDriverUrls(FirefoxDriverManager.java:95)
    at io.github.bonigarcia.wdm.WebDriverManager.createUrlHandler(WebDriverManager.java:1111)
    at io.github.bonigarcia.wdm.WebDriverManager.download(WebDriverManager.java:959)
    at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:877)
    at io.github.bonigarcia.wdm.WebDriverManager.fallback(WebDriverManager.java:1106)
    at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:1083)
    at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:883)
    at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:328)
----

To avoid this problem, Selenium-Jupiter can make authenticated requests using a https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token[personal access token]. See the <<advanced-configuration,advanced configuration>> section to discover how to set up this token in Selenium-Jupiter.

[discrete]
==== Testing localhost
A typical case in web development is testing a web application deployed in the local host. In this case, and when using browsers in Docker containers, we need to know that the address `localhost` inside a Docker container is not the host's address but the container address. To solve this problem, we can take different approaches. In Linux, we can use the gateway address for inter-container communication. This address is usually `172.17.0.1`, and can be discovered as follows:

[source,shell]
----
$ ip addr show docker0
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:b4:83:10:c8 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
----

When the host is Mac OS or Windows, we can use the DNS name `host.docker.internal`, which will be resolved to the internal IP address used by the host.

[discrete]
==== Chrome 92+ in Docker
There is an https://bugs.chromium.org/p/chromedriver/issues/detail?id=3857[open issue] with Chrome 92+ and Docker at the time of this writing. The problem can be solved to some extent by using the argument `--disable-gpu` in Chrome and Edge. This argument is used by Selenium-Jupiter 5 to avoid the issue. Nevertheless, some situations are still impossible to fix (e.g., when using https://hub.docker.com/r/bonigarcia/selenium-jupiter[Selenium-Jupiter in Docker] as CLI or Server).

== Community
There are two ways to try to get community support related to Selenium-Jupiter. First, questions about it can be discussed in https://stackoverflow.com/questions/tagged/selenium-jupiter_java[StackOverflow], using the tag _selenium-jupiter_. In addition, comments, suggestions, and bug-reporting should be made using the https://github.com/bonigarcia/selenium-jupiter/issues[GitHub issues]. Finally, if you think Selenium-Jupiter can be enhanced, consider contributing to the project through a  https://github.com/bonigarcia/selenium-jupiter/pulls[pull request].

== Support
https://opencollective.com/selenium-jupiter[Selenium-Jupiter] is part of https://opencollective.com/bonigarcia[OpenCollective], an online funding platform for open and transparent communities. You can support the project by contributing as a backer (i.e., a personal https://opencollective.com/selenium-jupiter/donate[donation] or https://opencollective.com/selenium-jupiter/contribute/backer-8132/checkout[recurring contribution]) or as a https://opencollective.com/selenium-jupiter/contribute/sponsor-8133/checkout[sponsor] (i.e., a recurring contribution by a company).

ifndef::backend-pdf[]
ifndef::backend-epub3[]
[discrete]
=== Backers
++++
include::backers.html[]
++++

[discrete]
=== Sponsors
++++
include::sponsors.html[]
++++
endif::[]
endif::[]

== Further Documentation
There are other resources related to Selenium-Jupiter and automated testing you can find helpful. For instance, the following journal papers:

* García, Boni, et al. "https://link.springer.com/article/10.1007%2Fs10664-021-09975-3[Automated driver management for Selenium WebDriver]." _Empirical Software Engineering_ 26.5 (2021): 1-51.
* García, Boni, et al. "https://www.mdpi.com/2079-9292/9/7/1067[A survey of the Selenium ecosystem]." _Electronics_ 9.7 (2020): 1067.
* García, Boni, et al. "https://www.mdpi.com/2079-9292/9/3/462[Assessment of QoE for video and audio in WebRTC applications using full-reference models]." _Electronics_ 9.3 (2020): 462.
* García, Boni, et al. "https://www.mdpi.com/2079-9292/8/8/854[Practical evaluation of VMAF perceptual video quality for WebRTC applications]." _Electronics_ 8.8 (2019): 854.
* García, Boni, et al. "https://ieeexplore.ieee.org/document/7992926/[WebRTC testing: challenges and practical solutions]." _IEEE Communications Standards Magazine_ 1.2 (2017): 36-42.
* García, Boni, and Juan Carlos Dueñas. "https://www.rintonpress.com/journals/jweonline.html#v14n56[Web browsing automation for applications quality control]." _Journal of web engineering_ (2015): 474-502.

Or the following book:

* García, Boni. https://www.amazon.com/Mastering-Software-Testing-JUnit-Comprehensive-ebook/dp/B076ZQCK5Q/[Mastering Software Testing with JUnit 5]. _Packt Publishing Ltd_, 2017.

== About
Selenium-Jupiter (Copyright © 2017-2021) is an open-source project created and maintained by https://bonigarcia.org/[Boni García] (https://twitter.com/boni_gg[@boni_gg]), licensed under the terms of https://www.apache.org/licenses/LICENSE-2.0[Apache 2.0 License]. This documentation (also available in link:selenium-jupiter.pdf[PDF] and link:selenium-jupiter.epub[EPUB]) is released under the terms of https://creativecommons.org/licenses/by-nc-sa/2.0/[CC BY-NC-SA 2.0].
