= *_Selenium-Jupiter_*: JUnit 5 extension for Selenium and Appium
Boni García <boni.garcia@urjc.es>
Version {project-version}

:revnumber: {project-version}
:example-caption!: 
ifndef::imagesdir[:imagesdir: img]
ifndef::sourcedir[:sourcedir: ../..]

http://junit.org/junit5/[JUnit 5] is the next generation of the well-known testing framework JUnit. _Jupiter_ is the name given to the new programming and extension model provided by JUnit 5. The extension model of JUnit 5, it allows to incorporate extra capabilities for JUnit 5 tests. On the other hand, http://www.seleniumhq.org/[Selenium] is a testing framework which allows to control local (_Selenium WebDriver_) or remote (_Selenium Grid_) browsers (e.g. Chrome, Firefox, and so on) programmatically to carry out automated testing of web applications. This documentation presents *_Selenium-Jupiter_*, a JUnit 5 extension aimed to provide seamless integration of Selenium (WebDriver and Grid) and Appium for JUnit 5 tests. _Selenium-Jupiter_ is open source (Apache 2.0 license) and is hosted on https://github.com/bonigarcia/selenium-jupiter[GitHub].

include::quick-reference.adoc[]

include::local-browsers.adoc[]

include::docker-browsers.adoc[]

include::remote-browsers.adoc[]

include::advanced.adoc[]

include::configuration.adoc[]

include::issues.adoc[]

include::about.adoc[]
