== Known issues

=== Testing localhost

A daily use case in web development is testing an web application deployed in a local server (_http://localhost:port/path_). In the case of using Docker browsers to test this web application, we need to be aware that _localhost_ inside a Docker container is not the local host anymore, but the container. To handle this issue, different approaches can be taken.

* If your host (i.e. the local machine running the tests and hosting the web application under test) is Linux, Docker creates a bridge named `docker0` by default. Both the Docker host and the Docker containers have an IP address on that bridge. We can find out the equivalent IP address to localhost using the following command (in this example, the address `172.17.0.1` will be used to replace localhost in our tests):  

[source]
----
$ ip addr show docker0
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:b4:83:10:c8 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
----

* If your host is Mac and using _Docker for Mac_, we can use the special DNS name `docker.for.mac.host.internal` which will resolve to the internal IP address used by the host.

* If your host is Windows and using _Docker for Windows_, we can use the special DNS name `docker.for.win.host.internal`.

=== Using old versions of Selenium

_Selenium-Jupiter_ requires *Selenium 3*. In fact, _selenium-java_ 3.x is incorporated as transitive dependency when using _Selenium-Jupiter_. Nevertheless, it might occur that an old version of Selenium (e.g. 2.x) is used in a project. In that case, _Selenium-Jupiter_ will typically fail as follows:

[source]
----
org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [...] in executable [...]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:221)
	...
Caused by: java.lang.NoClassDefFoundError: org/openqa/selenium/MutableCapabilities
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getDeclaredConstructor(Unknown Source)
	at io.github.bonigarcia.SeleniumExtension.getDriverHandler(SeleniumExtension.java:228)
	at io.github.bonigarcia.SeleniumExtension.resolveParameter(SeleniumExtension.java:175)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:207)
----

The solution is forcing the latest version of _selenium-java_ to 3.x.

For example, this issue is likely to happen in Spring-Boot 1.x projects. When using a Spring-Boot 1.x parent, Selenium 2 artifacts versions are established by default. To solve it, we need to force at least the following Selenium artifacts:

[source, xml]
----
    <properties>
        <selenium.version>3.11.0</selenium.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-api</artifactId>
            <version>${selenium.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>${selenium.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-firefox-driver</artifactId>
            <version>${selenium.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>${selenium.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
----

=== Recordings in Windows or Mac

Docker for Windows/Mac only mounts by default the home of your user (e.g. `C:\Users\your-user` in Windows). If _Selenium-Jupiter_ is executed from a different parent folder of that home, it won't be possible to write the MP4 recording (by default it uses the current folder, i.e. `.`). This configuration can be changed using the default mappings of in Docker for Windows/Mac settings.

As an alternative, the value of the configuration key `sel.jup.output.folder` of _Selenium-Jupiter_ can be used to some path inside the user folder (e.g. `C:\User\your-user\whatever`). The MP4 recording should end in there.
