== Known issues

=== Testing localhost

A daily use case in web development is testing an web application deployed in a local server (_http://localhost:port/path_). In the case of using Docker browsers to test this web application, we need to be aware that _localhost_ inside a Docker container is not the local host anymore, but the container. To handle this issue, different approaches can be taken.

* If your host (i.e. the local machine running the tests and hosting the web application under test) is Linux, Docker creates a bridge named `docker0` by default. Both the Docker host and the Docker containers have an IP address on that bridge. We can find out the equivalent IP address to localhost using the following command:

[source]
----
$ sudo ip addr show docker0
----

* If your host is Mac and using _Docker for Mac_, we can use the special DNS name `docker.for.mac.host.internal` which will resolve to the internal IP address used by the host.

* If your host is Windows and using _Docker for Windows_, we can use the special DNS name `docker.for.win.host.internal`.

=== Using old versions of Selenium

_Selenium-Jupiter_ requires *Selenium 3*. In fact, _selenium-java_ 3.x is incorporated as transitive dependency when using _Selenium-Jupiter_. Nevertheless, it might occur that an old version of Selenium (e.g. 2.x) is used in a project. In that case, _Selenium-Jupiter_ will typically fail as follows:

[source]
----
org.junit.jupiter.api.extension.ParameterResolutionException: Failed to resolve parameter [...] in executable [...]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:221)
	...
Caused by: java.lang.NoClassDefFoundError: org/openqa/selenium/MutableCapabilities
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getDeclaredConstructor(Unknown Source)
	at io.github.bonigarcia.SeleniumExtension.getDriverHandler(SeleniumExtension.java:228)
	at io.github.bonigarcia.SeleniumExtension.resolveParameter(SeleniumExtension.java:175)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:207)
----

The solution is forcing the latest version of _selenium-java_ to 3.x.

For example, this issue happens in Spring-Boot project 1.x. When using the Spring-Boot parent, Selenium artifacts versions are established in the parent. To solve it, we need to force typically the following artifacts:

[source, xml]
----
    <properties>
        <selenium.version>3.11.0</selenium.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-api</artifactId>
            <version>${selenium.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>${selenium.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-firefox-driver</artifactId>
            <version>${selenium.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>${selenium.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
----
