== Quick reference

*_Selenium-Jupiter_* has been built using the http://junit.org/junit5/docs/current/user-guide/#writing-tests-dependency-injection[dependency injection] capability provided by the extension model of JUnit 5. Thank to this feature, different types objects can be injected in JUnit 5 as methods or constructor parameters in `@Test` classes. Concretely, _Selenium-Jupiter_ allows to inject subtypes of the *WebDriver* interface (e.g. _ChromeDriver_, _FirefoxDriver_, and so on). 

Using _Selenium-Jupiter_ is very easy. First, you need to import the dependency in your project (typically as _test_ dependency). In Maven, it is done as follows:

[source,xml]
<dependency>
	<groupId>io.github.bonigarcia</groupId>
	<artifactId>selenium-jupiter</artifactId>
	<version>3.3.0</version>
	<scope>test</scope>
</dependency>

The dependency (typically _test_) to be declared in a Gradle project is as follows:

[source,json]
dependencies {
    testCompile("io.github.bonigarcia:selenium-jupiter:3.3.0")
}

NOTE: _Selenium-Jupiter_ 3.3.0 depends on *_selenium-java_ 3.141.59*, *_webdrivermanager_ 3.6.2*, *appium _java-client_ 7.0.0*, *spotify _docker-client_ 8.16.0*, and *selenide 5.2.6*. Therefore, by using the _Selenium-Jupiter_ dependency, these libraries will be added as transitive dependencies to your project.

Then, you need to declare _Selenium-Jupiter_ extension in your JUnit 5 test, simply annotating your test with `@ExtendWith(SeleniumExtension.class)`. Finally, you need to include one or more parameters in your `@Test` methods (or constructor) whose types implements the `WebDriver` interface (e.g. `ChromeDriver` to use Chrome, `FirefoxDriver` for Firefox, and so for). That's it. _Selenium-Jupiter_ control the lifecycle of the `WebDriver` object internally, and you just need to use the `WebDriver` object in your test to drive the browser(s) you want. For example:

[source,java]
----
include::../../test/java/io/github/bonigarcia/seljup/test/basic/ChromeAndFirefoxJupiterTest.java[tags=snippet-in-doc,indent=0]
----

NOTE: As of JUnit 5.1, extensions can be registered programmatically via `@RegisterExtension` or automatically via Java’s `ServiceLoader`. Both mechanisms can be used with _Selenium-Jupiter_.

The `WebDriver` subtypes supported by _Selenium-Jupiter_ are the following:

- `ChromeDriver`: Used to control Google Chrome browser.
- `FirefoxDriver`: Used to control Firefox browser.
- `EdgeDriver`: Used to control Microsoft Edge browser.
- `OperaDriver`: Used to control Opera browser.
- `SafariDriver`: Used to control Apple Safari browser (only possible in OSX El Capitan or greater).
- `HtmlUnitDriver`: Used to control HtmlUnit (headless browser).
- `PhantomJSDriver`: Used to control PhantomJS (headless browser).
- `InternetExplorerDriver`: Used to control Microsoft Internet Explorer.
- `RemoteWebDriver`: Used to control remote browsers (_Selenium Grid_).
- `AppiumDriver`: Used to control mobile devices (Android, iOS).

WARNING: The browser to be used must be installed in the machine running the test beforehand (except in the case of `RemoteWebDriver`, in which the requirement is to known a Selenium Server URL). In the case of mobile devices (`AppiumDriver`), the emulator should be up and running in local or available in a Appium Server identified by an URL.

You can also inject `WebDriver` objects declaring them as constructor parameters, instead of as test method parameters. For example as follows:

[source,java]
----
include::../../test/java/io/github/bonigarcia/seljup/test/constructor/ChromeInConstructorJupiterTest.java[tags=snippet-in-doc,indent=0]
----

This documentation contains a comprehensive collection of basic examples demonstrating the basic usage of _Selenium-Jupiter_ in JUnit 5 tests using different types of browsers. All these examples are part of the test suite of https://github.com/bonigarcia/selenium-jupiter[_Selenium-Jupiter_] and are executed on https://travis-ci.org/bonigarcia/selenium-jupiter[Travis CI]. 

