== Quick reference

*_Selenium-Jupiter_* has been built using the http://junit.org/junit5/docs/current/user-guide/#writing-tests-dependency-injection[dependency injection] capability provided by the extension model of JUnit 5. Thank to this feature, different types objects can be injected in JUnit 5 as methods or constructor parameters in `@Test` classes. Concretely, _Selenium-Jupiter_ allows to inject subtypes of the *WebDriver* interface (e.g. _ChromeDriver_, _FirefoxDriver_, and so on). 

Using _Selenium-Jupiter_ it's easy as pie. First, you need to import the dependency in your project (typically as _test_ dependency). In Maven, it is done as follows:

[source,xml]
<dependency>
	<groupId>io.github.bonigarcia</groupId>
	<artifactId>selenium-jupiter</artifactId>
	<version>2.1.0</version>
	<scope>test</scope>
</dependency>

NOTE: _Selenium-Jupiter_ 2.1.0 depends on *_selenium-java_ 3.11.0*, *_webdrivermanager_ 2.2.0*, *appium java-client 5.0.4*, and *docker-client 8.11.2*. Therefore, by using the _Selenium-Jupiter_ dependency, those libraries (_selenium-java_, _webdrivermanager_, _appium java-client_, and _docker-client_) will be added as transitive dependencies to your project.

Then, you need to declare _Selenium-Jupiter_ extension in your JUnit 5 test, simply annotating your test with `@ExtendWith(SeleniumExtension.class)`. Finally, you need to include one or more parameters in your `@Test` methods (or constructor) whose types implements the `WebDriver` interface (e.g. `ChromeDriver` to use Chrome, `FirefoxDriver` for Firefox, and so for). That's it. _Selenium-Jupiter_ control the lifecycle of the `WebDriver` object internally, and you just need to use the `WebDriver` object in your test to drive the browser(s) you want. For example:

[source,java]
----
include::../../test/java/io/github/bonigarcia/test/basic/ChromeAndFirefoxJupiterTest.java[tags=snippet-in-doc,indent=0]
----

The `WebDriver` subtypes supported by _Selenium-Jupiter_ are the following:

- `ChromeDriver`: Used to control Google Chrome browser.
- `FirefoxDriver`: Used to control Firefox browser.
- `EdgeDriver`: Used to control Microsoft Edge browser.
- `OperaDriver`: Used to control Opera browser.
- `SafariDriver`: Used to control Apple Safari browser (only possible in OSX El Capitan or greater).
- `HtmlUnitDriver`: Used to control HtmlUnit (headless browser).
- `PhantomJSDriver`: Used to control PhantomJS (headless browser).
- `InternetExplorerDriver`: Used to control Microsoft Internet Explorer. Although this browser is supported, Internet Explorer is deprecated (in favor of Edge) and its use is highly discouraged.
- `RemoteWebDriver`: Used to control remote browsers (_Selenium Grid_).
- `AppiumDriver`: Used to control mobile devices (Android, iOS).

WARNING: The browser to be used must be installed in the machine running the test beforehand (except in the case of `RemoteWebDriver`, in which the requirement is to known a Selenium Server URL). In the case of mobile devices (`AppiumDriver`), the emulator should be up and running in local or available in a Appium Server identified by an URL.

You can also inject `WebDriver` objects declaring them as constructor parameters, instead of as test method parameters. For example as follows:

[source,java]
----
include::../../test/java/io/github/bonigarcia/test/constructor/ChromeInConstructorJupiterTest.java[tags=snippet-in-doc,indent=0]
----

This documentation contains a comprehensive collection of basic examples demonstrating the basic usage of _seleniun-jupiter_ in JUnit 5 tests using different types of browsers. All these examples are part of the test suite of https://github.com/bonigarcia/selenium-jupiter[_Selenium-Jupiter_] and are executed on https://travis-ci.org/bonigarcia/selenium-jupiter[Travis CI]. 

