== Remote browsers

_Selenium-Jupiter_ also supports remote browsers, using a http://www.seleniumhq.org/projects/grid/[Selenium Grid] server. To that aim, a couple of custom annotations can be used:

* `DriverUrl` (_parameter-level_ or _field-level_): Annotation used to identify the URL value needed to instantiate a `RemoteWebDriver` object. This URL can be setup using the configuration key `sel.jup.selenium.server.url`. This value can be used to use browsers from cloud providers, such as https://saucelabs.com/[Saucelabs] or https://www.browserstack.com/[BrowserStack].
* `DriverCapabilities` (_parameter-level_ or _field-level_): Annotation to configure the desired _capabilities_ (WebDriver's object `DesiredCapabilities`).

=== Using capabilities

The annotation `@DriverCapabilities` is used to specify WebDriver capabilities (i.e. type browser, version, platform, etc.). These capabilities are typically used for Selenium Grid tests (i.e. tests using remote browsers). To that aim, a Selenium Hub (also known as _Selenium Server_) should be up an running, and its URL should known. This URL will be specified using the _Selenium-Jupiter_ annotation `@DriverUrl`. 

The following example provides a complete https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/advance/RemoteWebDriverJupiterTest.java[example] about this. As you can see, in the test setup (`@BeforeAll`) a Selenium Grid is implemented, first starting a Hub (a.k.a. _Selenium Server_), and then a couple of nodes (Chrome a Firefox) are registered in the Hub. Therefore, remote test using `RemoteWebDriver` can be executed, simply pointing to the Hub (whose URL in this case is `http://localhost:4444/wd/hub` in this example) and selecting the browser to be used using the `Capabilities`.

[source,java]
----
include::../../test/java/io/github/bonigarcia/seljup/test/advance/RemoteWebDriverJupiterTest.java[tags=snippet-in-doc,indent=0]
----

The following class contains an example which uses Chrome as browser and capabilities defined using `@DriverCapabilities`. Concretely, this example uses the mobile emulation feature provided out of the box by Chrome (i.e. render the web page using small screen resolutions to emulate smartphones).

[source,java]
----
include::../../test/java/io/github/bonigarcia/seljup/test/advance/ChromeWithGlobalCapabilitiesJupiterTest.java[tags=snippet-in-doc,indent=0]
----

=== Mobile testing with Appium

The annotation `@DriverCapabilities` can be also used to specify the desired capabilities to create an instances of AppiumDriver to drive mobile devices (Android or iOS). If not `@DriverUrl` is specified, _Selenium-Jupiter_ will start automatically an instance of Appium Server (by default in port 4723) in the localhost after each test execution (this server is shutdown before each test). For example:

[source,java]
----
include::../../test/java/io/github/bonigarcia/seljup/test/advance/AppiumChromeJupiterTest.java[tags=snippet-in-doc,indent=0]
----

We can also specify a custom Appium Server URL changing the value of `@DriverUrl`, at field-level or parameter-level:

[source,java]
----
include::../../test/java/io/github/bonigarcia/seljup/test/advance/AppiumWithGlobalOptionsChromeJupiterTest.java[tags=snippet-in-doc,indent=0]
----


